version: '3'

services:
  watchflix-ci:
    build:
      context: ./api
    restart: on-failure
    volumes:
      - ./api:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    env_file:
      - env/dev.env
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    command:
      - /bin/sh
      - -c
      - dockerize -wait http://elasticsearch:9200/_cluster/health -timeout 3m yarn install && yarn seed -- --movies=resources/movie-data.csv --users=resources/user-preference.js --credits=resources/credits-data.csv && yarn run-watch

  mongo:
    image: "mongo:4.0.5"
    ports:
      - "27017:27017"
    depends_on:
      - elasticsearch
    volumes:
      - './data:/data/db'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
    - "9300:9300"
    - "9200:9200"

#https://blog.patricktriest.com/text-search-docker-elasticsearch/
