version: '3'

services:
  watchflix:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    env_file:
      - env/dev.env
    links:
      - mongo
  mongo:
    image: "mongo:4.0.5"
    ports:
      - "27017:27017"
