version: '3.4'

services:
  watchflix:
    build:
      context: ./api
      target: ci
    image: watchflix:latest
    volumes:
      - ./api:/app
      - /app/node_modules/
    env_file:
      - env/test.env
    links:
      - mongo
    command:
      - /bin/sh
      - -c
      - yarn --pure-lockfile && yarn test:ci
  mongo:
    image: "mongo:4.0.5"
    ports:
      - "27018:27018"
