version: '3'

services:
  watchflix:
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    env_file:
      - env/dev.env
    links:
      - mongo
    command:
      - /bin/sh
      - -c
      - yarn seed -- --movies=resources/movie-data.csv --users=resources/user-preference.js --credits=resources/credits-data.csv && yarn run-watch

  mongo:
    image: "mongo:4.0.5"
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
