version: '3'

services:
  watchflix:
    build:
      context: ./api
    restart: on-failure
    volumes:
      - ./api:/app
      - /app/node_modules/
    env_file:
      - env/test.env
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    command:
      - /bin/sh
      - -c
      - dockerize -wait http://elasticsearch:9200/_cluster/health -timeout 3m yarn --pure-lockfile && yarn test

  mongo:
    image: "mongo:4.0.5"
    ports:
      - "27018:27018"
    depends_on:
      - elasticsearch
    volumes:
      - './data:/data/db'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9301:9300"
      - "9201:9200"

#https://blog.patricktriest.com/text-search-docker-elasticsearch/
