version: '3'

services:
  whatflix:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    env_file:
      - env/dev.env
    links:
      - mongo
  mongo:
    image: "mongo:3.6.3"
    ports:
      - "27017:27017"
